os: Visual Studio 2019
skip_branch_with_pr: true
configuration:
  - Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_API_KEY:
    secure: nyYYvfNcljaFo6s6IBdC3lhqwAKOC9HfQjPguKXoHfgs22MwakH+IeXrM2Xn1uc0
  NUGET_URL: https://www.nuget.org/api/v2/package
  GITHUB_API_KEY:
    secure: E3k8jpbA+1HCY5PHHiUlaOTJVBSlJyGNUGdIAUTStkSs9Aw8b5jYJ8bMZv+9/nb+
  SONAR_KEY:
    secure: tcSHmNZmnvw9va+hvM0+3Fsmhnifp8sAG0RJ8hf7OTd7i6TghR6ZXHx7Il/C79J0
  COVERALLS_TOKEN:
    secure: b+QSzRug1thjPESkOeDjHBzrEH2diPgWiCKX42E8u7l2ls//LN1EWpHXHkkphtGj

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

# Build cache
cache:
  - tools -> build.cake
